# Use postgres/example user/password credentials
version: '3.1'

services:
 db:
  image: rolfkristensen/postgres-milage:1.0
  restart: always
  environment:
   POSTGRES_PASSWORD: test
  volumes:
   - pgdata:/var/lib/postgresql/data
  ports:
   - 9543:5432
  networks:
   db:

 adminer:
  image: adminer
  restart: always
  ports:
   - 9000:8080
  networks:
   db:

volumes:
 pgdata: 

networks:
 db:
